namespace DocumentFormat.OpenXml.Flatten.Compatibilities.Packaging;

partial class CompatiblePackage
{
    private static class MimeUtility
    {
        public static string? LookupType(string type)
        {
            // 这是从 MimeMapping 抄的
            switch (type)
            {
                case "123":
                    return "application/vnd.lotus-1-2-3";
                case "3dml":
                    return "text/vnd.in3d.3dml";
                case "3ds":
                    return "image/x-3ds";
                case "3g2":
                    return "video/3gpp2";
                case "3gp":
                case "3gpp":
                    return "video/3gpp";
                case "7z":
                    return "application/x-7z-compressed";
                case "aab":
                case "u32":
                case "vox":
                case "x32":
                    return "application/x-authorware-bin";
                case "aac":
                    return "audio/x-aac";
                case "aam":
                    return "application/x-authorware-map";
                case "aas":
                    return "application/x-authorware-seg";
                case "abw":
                    return "application/x-abiword";
                case "ac":
                    return "application/pkix-attr-cert";
                case "acc":
                    return "application/vnd.americandynamics.acc";
                case "ace":
                    return "application/x-ace-compressed";
                case "acu":
                    return "application/vnd.acucobol";
                case "acutc":
                case "atc":
                    return "application/vnd.acucorp";
                case "adp":
                    return "audio/adpcm";
                case "aep":
                    return "application/vnd.audiograph";
                case "afm":
                case "pfa":
                case "pfb":
                case "pfm":
                    return "application/x-font-type1";
                case "afp":
                case "list3820":
                case "listafp":
                    return "application/vnd.ibm.modcap";
                case "ahead":
                    return "application/vnd.ahead.space";
                case "ai":
                case "eps":
                case "ps":
                    return "application/postscript";
                case "aif":
                case "aifc":
                case "aiff":
                    return "audio/x-aiff";
                case "air":
                    return "application/vnd.adobe.air-application-installer-package+zip";
                case "ait":
                    return "application/vnd.dvb.ait";
                case "ami":
                    return "application/vnd.amiga.ami";
                case "apk":
                    return "application/vnd.android.package-archive";
                case "apng":
                    return "image/apng";
                case "appcache":
                case "manifest":
                    return "text/cache-manifest";
                case "application":
                    return "application/x-ms-application";
                case "apr":
                    return "application/vnd.lotus-approach";
                case "arc":
                    return "application/x-freearc";
                case "arj":
                    return "application/x-arj";
                case "asc":
                case "sig":
                    return "application/pgp-signature";
                case "asf":
                case "asx":
                    return "video/x-ms-asf";
                case "asm":
                case "s":
                    return "text/x-asm";
                case "aso":
                    return "application/vnd.accpac.simply.aso";
                case "atom":
                    return "application/atom+xml";
                case "atomcat":
                    return "application/atomcat+xml";
                case "atomsvc":
                    return "application/atomsvc+xml";
                case "atx":
                    return "application/vnd.antix.game-component";
                case "au":
                case "snd":
                    return "audio/basic";
                case "avi":
                    return "video/x-msvideo";
                case "aw":
                    return "application/applixware";
                case "azf":
                    return "application/vnd.airzip.filesecure.azf";
                case "azs":
                    return "application/vnd.airzip.filesecure.azs";
                case "azw":
                    return "application/vnd.amazon.ebook";
                case "bat":
                case "com":
                case "dll":
                case "exe":
                case "msi":
                    return "application/x-msdownload";
                case "bbaw":
                    return "application/x-bb-appworld";
                case "bcpio":
                    return "application/x-bcpio";
                case "bdf":
                    return "application/x-font-bdf";
                case "bdm":
                    return "application/vnd.syncml.dm+wbxml";
                case "bdoc":
                    return "application/bdoc";
                case "bed":
                    return "application/vnd.realvnc.bed";
                case "bh2":
                    return "application/vnd.fujitsu.oasysprs";
                case "bin":
                case "bpk":
                case "buffer":
                case "deploy":
                case "dist":
                case "distz":
                case "dms":
                case "dump":
                case "elc":
                case "img":
                case "lrf":
                case "mar":
                case "msm":
                case "msp":
                case "pkg":
                case "safariextz":
                case "so":
                    return "application/octet-stream";
                case "blb":
                case "blorb":
                    return "application/x-blorb";
                case "bmi":
                    return "application/vnd.bmi";
                case "bmp":
                    return "image/bmp";
                case "book":
                case "fm":
                case "frame":
                case "maker":
                    return "application/vnd.framemaker";
                case "box":
                    return "application/vnd.previewsystems.box";
                case "boz":
                case "bz2":
                    return "application/x-bzip2";
                case "btif":
                    return "image/prs.btif";
                case "bz":
                    return "application/x-bzip";
                case "c":
                case "cc":
                case "cpp":
                case "cxx":
                case "dic":
                case "h":
                case "hh":
                    return "text/x-c";
                case "c11amc":
                    return "application/vnd.cluetrust.cartomobile-config";
                case "c11amz":
                    return "application/vnd.cluetrust.cartomobile-config-pkg";
                case "c4d":
                case "c4f":
                case "c4g":
                case "c4p":
                case "c4u":
                    return "application/vnd.clonk.c4group";
                case "cab":
                    return "application/vnd.ms-cab-compressed";
                case "caf":
                    return "audio/x-caf";
                case "cap":
                case "dmp":
                case "pcap":
                    return "application/vnd.tcpdump.pcap";
                case "car":
                    return "application/vnd.curl.car";
                case "cat":
                    return "application/vnd.ms-pki.seccat";
                case "cb7":
                case "cba":
                case "cbr":
                case "cbt":
                case "cbz":
                    return "application/x-cbr";
                case "cco":
                    return "application/x-cocoa";
                case "cct":
                case "cst":
                case "cxt":
                case "dcr":
                case "dir":
                case "dxr":
                case "fgd":
                case "swa":
                case "w3d":
                    return "application/x-director";
                case "ccxml":
                    return "application/ccxml+xml";
                case "cdbcmsg":
                    return "application/vnd.contact.cmsg";
                case "cdf":
                case "nc":
                    return "application/x-netcdf";
                case "cdkey":
                    return "application/vnd.mediastation.cdkey";
                case "cdmia":
                    return "application/cdmi-capability";
                case "cdmic":
                    return "application/cdmi-container";
                case "cdmid":
                    return "application/cdmi-domain";
                case "cdmio":
                    return "application/cdmi-object";
                case "cdmiq":
                    return "application/cdmi-queue";
                case "cdx":
                    return "chemical/x-cdx";
                case "cdxml":
                    return "application/vnd.chemdraw+xml";
                case "cdy":
                    return "application/vnd.cinderella";
                case "cer":
                    return "application/pkix-cert";
                case "cfs":
                    return "application/x-cfs-compressed";
                case "cgm":
                    return "image/cgm";
                case "chat":
                    return "application/x-chat";
                case "chm":
                    return "application/vnd.ms-htmlhelp";
                case "chrt":
                    return "application/vnd.kde.kchart";
                case "cif":
                    return "chemical/x-cif";
                case "cii":
                    return "application/vnd.anser-web-certificate-issue-initiation";
                case "cil":
                    return "application/vnd.ms-artgalry";
                case "cla":
                    return "application/vnd.claymore";
                case "class":
                    return "application/java-vm";
                case "clkk":
                    return "application/vnd.crick.clicker.keyboard";
                case "clkp":
                    return "application/vnd.crick.clicker.palette";
                case "clkt":
                    return "application/vnd.crick.clicker.template";
                case "clkw":
                    return "application/vnd.crick.clicker.wordbank";
                case "clkx":
                    return "application/vnd.crick.clicker";
                case "clp":
                    return "application/x-msclip";
                case "cmc":
                    return "application/vnd.cosmocaller";
                case "cmdf":
                    return "chemical/x-cmdf";
                case "cml":
                    return "chemical/x-cml";
                case "cmp":
                    return "application/vnd.yellowriver-custom-menu";
                case "cmx":
                    return "image/x-cmx";
                case "cod":
                    return "application/vnd.rim.cod";
                case "coffee":
                case "litcoffee":
                    return "text/coffeescript";
                case "conf":
                case "def":
                case "in":
                case "ini":
                case "list":
                case "log":
                case "text":
                case "txt":
                    return "text/plain";
                case "cpio":
                    return "application/x-cpio";
                case "cpt":
                    return "application/mac-compactpro";
                case "crd":
                    return "application/x-mscardfile";
                case "crl":
                    return "application/pkix-crl";
                case "crt":
                case "der":
                case "pem":
                    return "application/x-x509-ca-cert";
                case "crx":
                    return "application/x-chrome-extension";
                case "cryptonote":
                    return "application/vnd.rig.cryptonote";
                case "csh":
                    return "application/x-csh";
                case "csl":
                    return "application/vnd.citationstyles.style+xml";
                case "csml":
                    return "chemical/x-csml";
                case "csp":
                    return "application/vnd.commonspace";
                case "css":
                    return "text/css";
                case "csv":
                    return "text/csv";
                case "cu":
                    return "application/cu-seeme";
                case "cur":
                case "ico":
                    return "image/x-icon";
                case "curl":
                    return "text/vnd.curl";
                case "cww":
                    return "application/prs.cww";
                case "dae":
                    return "model/vnd.collada+xml";
                case "daf":
                    return "application/vnd.mobius.daf";
                case "dart":
                    return "application/vnd.dart";
                case "dataless":
                case "seed":
                    return "application/vnd.fdsn.seed";
                case "davmount":
                    return "application/davmount+xml";
                case "dbk":
                    return "application/docbook+xml";
                case "dcurl":
                    return "text/vnd.curl.dcurl";
                case "dd2":
                    return "application/vnd.oma.dd2+xml";
                case "ddd":
                    return "application/vnd.fujixerox.ddd";
                case "dds":
                    return "image/vnd.ms-dds";
                case "deb":
                case "udeb":
                    return "application/x-debian-package";
                case "dfac":
                    return "application/vnd.dreamfactory";
                case "dgc":
                    return "application/x-dgc-compressed";
                case "dis":
                    return "application/vnd.mobius.dis";
                case "djv":
                case "djvu":
                    return "image/vnd.djvu";
                case "dmg":
                    return "application/x-apple-diskimage";
                case "dna":
                    return "application/vnd.dna";
                case "doc":
                case "dot":
                    return "application/msword";
                case "docm":
                    return "application/vnd.ms-word.document.macroenabled.12";
                case "docx":
                    return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
                case "dotm":
                    return "application/vnd.ms-word.template.macroenabled.12";
                case "dotx":
                    return "application/vnd.openxmlformats-officedocument.wordprocessingml.template";
                case "dp":
                    return "application/vnd.osgi.dp";
                case "dpg":
                    return "application/vnd.dpgraph";
                case "dra":
                    return "audio/vnd.dra";
                case "dsc":
                    return "text/prs.lines.tag";
                case "dssc":
                    return "application/dssc+der";
                case "dtb":
                    return "application/x-dtbook+xml";
                case "dtd":
                    return "application/xml-dtd";
                case "dts":
                    return "audio/vnd.dts";
                case "dtshd":
                    return "audio/vnd.dts.hd";
                case "dvb":
                    return "video/vnd.dvb.file";
                case "dvi":
                    return "application/x-dvi";
                case "dwf":
                    return "model/vnd.dwf";
                case "dwg":
                    return "image/vnd.dwg";
                case "dxf":
                    return "image/vnd.dxf";
                case "dxp":
                    return "application/vnd.spotfire.dxp";
                case "ear":
                case "jar":
                case "war":
                    return "application/java-archive";
                case "ecelp4800":
                    return "audio/vnd.nuera.ecelp4800";
                case "ecelp7470":
                    return "audio/vnd.nuera.ecelp7470";
                case "ecelp9600":
                    return "audio/vnd.nuera.ecelp9600";
                case "ecma":
                case "es":
                    return "application/ecmascript";
                case "edm":
                    return "application/vnd.novadigm.edm";
                case "edx":
                    return "application/vnd.novadigm.edx";
                case "efif":
                    return "application/vnd.picsel";
                case "ei6":
                    return "application/vnd.pg.osasli";
                case "emf":
                case "emz":
                case "wmf":
                    return "application/x-msmetafile";
                case "eml":
                case "mime":
                    return "message/rfc822";
                case "emma":
                    return "application/emma+xml";
                case "eol":
                    return "audio/vnd.digital-winds";
                case "eot":
                    return "application/vnd.ms-fontobject";
                case "epub":
                    return "application/epub+zip";
                case "es3":
                case "et3":
                    return "application/vnd.eszigno3+xml";
                case "esa":
                    return "application/vnd.osgi.subsystem";
                case "esf":
                    return "application/vnd.epson.esf";
                case "etx":
                    return "text/x-setext";
                case "eva":
                    return "application/x-eva";
                case "evy":
                    return "application/x-envoy";
                case "exi":
                    return "application/exi";
                case "ext":
                    return "application/vnd.novadigm.ext";
                case "ez":
                    return "application/andrew-inset";
                case "ez2":
                    return "application/vnd.ezpix-album";
                case "ez3":
                    return "application/vnd.ezpix-package";
                case "f":
                case "f77":
                case "f90":
                case "for":
                    return "text/x-fortran";
                case "f4a":
                case "f4b":
                case "m4a":
                case "mp4a":
                    return "audio/mp4";
                case "f4p":
                case "mp4":
                case "mp4v":
                case "mpg4":
                    return "video/mp4";
                case "f4v":
                    return "video/x-f4v";
                case "fbs":
                    return "image/vnd.fastbidsheet";
                case "fcdt":
                    return "application/vnd.adobe.formscentral.fcdt";
                case "fcs":
                    return "application/vnd.isac.fcs";
                case "fdf":
                    return "application/vnd.fdf";
                case "fe_launch":
                    return "application/vnd.denovo.fcselayout-link";
                case "fg5":
                    return "application/vnd.fujitsu.oasysgp";
                case "fh":
                case "fh4":
                case "fh5":
                case "fh7":
                case "fhc":
                    return "image/x-freehand";
                case "fig":
                    return "application/x-xfig";
                case "flac":
                    return "audio/x-flac";
                case "fli":
                    return "video/x-fli";
                case "flo":
                    return "application/vnd.micrografx.flo";
                case "flv":
                    return "video/x-flv";
                case "flw":
                    return "application/vnd.kde.kivio";
                case "flx":
                    return "text/vnd.fmi.flexstor";
                case "fly":
                    return "text/vnd.fly";
                case "fnc":
                    return "application/vnd.frogans.fnc";
                case "fpx":
                    return "image/vnd.fpx";
                case "fsc":
                    return "application/vnd.fsc.weblaunch";
                case "fst":
                    return "image/vnd.fst";
                case "ftc":
                    return "application/vnd.fluxtime.clip";
                case "fti":
                    return "application/vnd.anser-web-funds-transfer-initiation";
                case "fvt":
                    return "video/vnd.fvt";
                case "fxp":
                case "fxpl":
                    return "application/vnd.adobe.fxp";
                case "fzs":
                    return "application/vnd.fuzzysheet";
                case "g2w":
                    return "application/vnd.geoplan";
                case "g3":
                    return "image/g3fax";
                case "g3w":
                    return "application/vnd.geospace";
                case "gac":
                    return "application/vnd.groove-account";
                case "gam":
                    return "application/x-tads";
                case "gbr":
                    return "application/rpki-ghostbusters";
                case "gca":
                    return "application/x-gca-compressed";
                case "gdl":
                    return "model/vnd.gdl";
                case "gdoc":
                    return "application/vnd.google-apps.document";
                case "geo":
                    return "application/vnd.dynageo";
                case "geojson":
                    return "application/geo+json";
                case "gex":
                case "gre":
                    return "application/vnd.geometry-explorer";
                case "ggb":
                    return "application/vnd.geogebra.file";
                case "ggt":
                    return "application/vnd.geogebra.tool";
                case "ghf":
                    return "application/vnd.groove-help";
                case "gif":
                    return "image/gif";
                case "gim":
                    return "application/vnd.groove-identity-message";
                case "gml":
                    return "application/gml+xml";
                case "gmx":
                    return "application/vnd.gmx";
                case "gnumeric":
                    return "application/x-gnumeric";
                case "gph":
                    return "application/vnd.flographit";
                case "gpx":
                    return "application/gpx+xml";
                case "gqf":
                case "gqs":
                    return "application/vnd.grafeq";
                case "gram":
                    return "application/srgs";
                case "gramps":
                    return "application/x-gramps-xml";
                case "grv":
                    return "application/vnd.groove-injector";
                case "grxml":
                    return "application/srgs+xml";
                case "gsf":
                    return "application/x-font-ghostscript";
                case "gsheet":
                    return "application/vnd.google-apps.spreadsheet";
                case "gslides":
                    return "application/vnd.google-apps.presentation";
                case "gtar":
                    return "application/x-gtar";
                case "gtm":
                    return "application/vnd.groove-tool-message";
                case "gtw":
                    return "model/vnd.gtw";
                case "gv":
                    return "text/vnd.graphviz";
                case "gxf":
                    return "application/gxf";
                case "gxt":
                    return "application/vnd.geonext";
                case "gz":
                    return "application/gzip";
                case "h261":
                    return "video/h261";
                case "h263":
                    return "video/h263";
                case "h264":
                    return "video/h264";
                case "hal":
                    return "application/vnd.hal+xml";
                case "hbci":
                    return "application/vnd.hbci";
                case "hbs":
                    return "text/x-handlebars-template";
                case "hdd":
                    return "application/x-virtualbox-hdd";
                case "hdf":
                    return "application/x-hdf";
                case "hdp":
                case "jxr":
                    return "image/jxr";
                case "heic":
                    return "image/heic";
                case "heics":
                    return "image/heic-sequence";
                case "heif":
                    return "image/heif";
                case "heifs":
                    return "image/heif-sequence";
                case "hjson":
                    return "application/hjson";
                case "hlp":
                    return "application/winhlp";
                case "hpgl":
                    return "application/vnd.hp-hpgl";
                case "hpid":
                    return "application/vnd.hp-hpid";
                case "hps":
                    return "application/vnd.hp-hps";
                case "hqx":
                    return "application/mac-binhex40";
                case "htc":
                    return "text/x-component";
                case "htke":
                    return "application/vnd.kenameaapp";
                case "htm":
                case "html":
                case "shtml":
                    return "text/html";
                case "hvd":
                    return "application/vnd.yamaha.hv-dic";
                case "hvp":
                    return "application/vnd.yamaha.hv-voice";
                case "hvs":
                    return "application/vnd.yamaha.hv-script";
                case "i2g":
                    return "application/vnd.intergeo";
                case "icc":
                case "icm":
                    return "application/vnd.iccprofile";
                case "ice":
                    return "x-conference/x-cooltalk";
                case "ics":
                case "ifb":
                    return "text/calendar";
                case "ief":
                    return "image/ief";
                case "ifm":
                    return "application/vnd.shana.informed.formdata";
                case "iges":
                case "igs":
                    return "model/iges";
                case "igl":
                    return "application/vnd.igloader";
                case "igm":
                    return "application/vnd.insors.igm";
                case "igx":
                    return "application/vnd.micrografx.igx";
                case "iif":
                    return "application/vnd.shana.informed.interchange";
                case "imp":
                    return "application/vnd.accpac.simply.imp";
                case "ims":
                    return "application/vnd.ms-ims";
                case "ink":
                case "inkml":
                    return "application/inkml+xml";
                case "install":
                    return "application/x-install-instructions";
                case "iota":
                    return "application/vnd.astraea-software.iota";
                case "ipfix":
                    return "application/ipfix";
                case "ipk":
                    return "application/vnd.shana.informed.package";
                case "irm":
                    return "application/vnd.ibm.rights-management";
                case "irp":
                    return "application/vnd.irepository.package+xml";
                case "iso":
                    return "application/x-iso9660-image";
                case "itp":
                    return "application/vnd.shana.informed.formtemplate";
                case "ivp":
                    return "application/vnd.immervision-ivp";
                case "ivu":
                    return "application/vnd.immervision-ivu";
                case "jad":
                    return "text/vnd.sun.j2me.app-descriptor";
                case "jade":
                    return "text/jade";
                case "jam":
                    return "application/vnd.jam";
                case "jardiff":
                    return "application/x-java-archive-diff";
                case "java":
                    return "text/x-java-source";
                case "jisp":
                    return "application/vnd.jisp";
                case "jlt":
                    return "application/vnd.hp-jlyt";
                case "jng":
                    return "image/x-jng";
                case "jnlp":
                    return "application/x-java-jnlp-file";
                case "joda":
                    return "application/vnd.joost.joda-archive";
                case "jp2":
                case "jpg2":
                    return "image/jp2";
                case "jpe":
                case "jpeg":
                case "jpg":
                    return "image/jpeg";
                case "jpf":
                case "jpx":
                    return "image/jpx";
                case "jpgm":
                case "jpm":
                    return "video/jpm";
                case "jpgv":
                    return "video/jpeg";
                case "js":
                    return "application/javascript";
                case "json":
                case "map":
                case "topojson":
                    return "application/json";
                case "json5":
                    return "application/json5";
                case "jsonld":
                    return "application/ld+json";
                case "jsonml":
                    return "application/jsonml+json";
                case "jsx":
                    return "text/jsx";
                case "kar":
                case "mid":
                case "midi":
                case "rmi":
                    return "audio/midi";
                case "karbon":
                    return "application/vnd.kde.karbon";
                case "kdbx":
                    return "application/x-keepass2";
                case "kfo":
                    return "application/vnd.kde.kformula";
                case "kia":
                    return "application/vnd.kidspiration";
                case "kml":
                    return "application/vnd.google-earth.kml+xml";
                case "kmz":
                    return "application/vnd.google-earth.kmz";
                case "kne":
                case "knp":
                    return "application/vnd.kinar";
                case "kon":
                    return "application/vnd.kde.kontour";
                case "kpr":
                case "kpt":
                    return "application/vnd.kde.kpresenter";
                case "kpxx":
                    return "application/vnd.ds-keypoint";
                case "ksp":
                    return "application/vnd.kde.kspread";
                case "ktr":
                case "ktz":
                    return "application/vnd.kahootz";
                case "ktx":
                    return "image/ktx";
                case "kwd":
                case "kwt":
                    return "application/vnd.kde.kword";
                case "lasxml":
                    return "application/vnd.las.las+xml";
                case "latex":
                    return "application/x-latex";
                case "lbd":
                    return "application/vnd.llamagraphics.life-balance.desktop";
                case "lbe":
                    return "application/vnd.llamagraphics.life-balance.exchange+xml";
                case "les":
                    return "application/vnd.hhe.lesson-player";
                case "less":
                    return "text/less";
                case "lha":
                case "lzh":
                    return "application/x-lzh-compressed";
                case "link66":
                    return "application/vnd.route66.link66+xml";
                case "lnk":
                    return "application/x-ms-shortcut";
                case "lostxml":
                    return "application/lost+xml";
                case "lrm":
                    return "application/vnd.ms-lrm";
                case "ltf":
                    return "application/vnd.frogans.ltf";
                case "lua":
                    return "text/x-lua";
                case "luac":
                    return "application/x-lua-bytecode";
                case "lvp":
                    return "audio/vnd.lucent.voice";
                case "lwp":
                    return "application/vnd.lotus-wordpro";
                case "m13":
                case "m14":
                case "mvb":
                    return "application/x-msmediaview";
                case "m1v":
                case "m2v":
                case "mpe":
                case "mpeg":
                case "mpg":
                    return "video/mpeg";
                case "m21":
                case "mp21":
                    return "application/mp21";
                case "m2a":
                case "m3a":
                case "mp2":
                case "mp2a":
                case "mp3":
                case "mpga":
                    return "audio/mpeg";
                case "m3u":
                    return "audio/x-mpegurl";
                case "m3u8":
                    return "application/vnd.apple.mpegurl";
                case "m4p":
                case "mp4s":
                    return "application/mp4";
                case "m4u":
                case "mxu":
                    return "video/vnd.mpegurl";
                case "m4v":
                    return "video/x-m4v";
                case "ma":
                case "mb":
                case "nb":
                    return "application/mathematica";
                case "mads":
                    return "application/mads+xml";
                case "mag":
                    return "application/vnd.ecowin.chart";
                case "man":
                case "me":
                case "ms":
                case "roff":
                case "t":
                case "tr":
                    return "text/troff";
                case "markdown":
                case "md":
                    return "text/markdown";
                case "mathml":
                    return "application/mathml+xml";
                case "mbk":
                    return "application/vnd.mobius.mbk";
                case "mbox":
                    return "application/mbox";
                case "mc1":
                    return "application/vnd.medcalcdata";
                case "mcd":
                    return "application/vnd.mcd";
                case "mcurl":
                    return "text/vnd.curl.mcurl";
                case "mdb":
                    return "application/x-msaccess";
                case "mdi":
                    return "image/vnd.ms-modi";
                case "mdx":
                    return "text/mdx";
                case "mesh":
                case "msh":
                case "silo":
                    return "model/mesh";
                case "meta4":
                    return "application/metalink4+xml";
                case "metalink":
                    return "application/metalink+xml";
                case "mets":
                    return "application/mets+xml";
                case "mfm":
                    return "application/vnd.mfmp";
                case "mft":
                    return "application/rpki-manifest";
                case "mgp":
                    return "application/vnd.osgeo.mapguide.package";
                case "mgz":
                    return "application/vnd.proteus.magazine";
                case "mie":
                    return "application/x-mie";
                case "mif":
                    return "application/vnd.mif";
                case "mj2":
                case "mjp2":
                    return "video/mj2";
                case "mjs":
                    return "text/javascript";
                case "mk3d":
                case "mks":
                case "mkv":
                    return "video/x-matroska";
                case "mka":
                    return "audio/x-matroska";
                case "mkd":
                    return "text/x-markdown";
                case "mlp":
                    return "application/vnd.dolby.mlp";
                case "mmd":
                    return "application/vnd.chipnuts.karaoke-mmd";
                case "mmf":
                    return "application/vnd.smaf";
                case "mml":
                    return "text/mathml";
                case "mmr":
                    return "image/vnd.fujixerox.edmics-mmr";
                case "mng":
                    return "video/x-mng";
                case "mny":
                    return "application/x-msmoney";
                case "mobi":
                case "prc":
                    return "application/x-mobipocket-ebook";
                case "mods":
                    return "application/mods+xml";
                case "mov":
                case "qt":
                    return "video/quicktime";
                case "movie":
                    return "video/x-sgi-movie";
                case "mpc":
                    return "application/vnd.mophun.certificate";
                case "mpd":
                    return "application/dash+xml";
                case "mpkg":
                    return "application/vnd.apple.installer+xml";
                case "mpm":
                    return "application/vnd.blueice.multipass";
                case "mpn":
                    return "application/vnd.mophun.application";
                case "mpp":
                case "mpt":
                    return "application/vnd.ms-project";
                case "mpy":
                    return "application/vnd.ibm.minipay";
                case "mqy":
                    return "application/vnd.mobius.mqy";
                case "mrc":
                    return "application/marc";
                case "mrcx":
                    return "application/marcxml+xml";
                case "mscml":
                    return "application/mediaservercontrol+xml";
                case "mseed":
                    return "application/vnd.fdsn.mseed";
                case "mseq":
                    return "application/vnd.mseq";
                case "msf":
                    return "application/vnd.epson.msf";
                case "msg":
                    return "application/vnd.ms-outlook";
                case "msl":
                    return "application/vnd.mobius.msl";
                case "msty":
                    return "application/vnd.muvee.style";
                case "mts":
                    return "model/vnd.mts";
                case "mus":
                    return "application/vnd.musician";
                case "musicxml":
                    return "application/vnd.recordare.musicxml+xml";
                case "mwf":
                    return "application/vnd.mfer";
                case "mxf":
                    return "application/mxf";
                case "mxl":
                    return "application/vnd.recordare.musicxml";
                case "mxmf":
                    return "audio/mobile-xmf";
                case "mxml":
                case "xhvml":
                case "xvm":
                case "xvml":
                    return "application/xv+xml";
                case "mxs":
                    return "application/vnd.triscape.mxs";
                case "n-gage":
                    return "application/vnd.nokia.n-gage.symbian.install";
                case "n3":
                    return "text/n3";
                case "nbp":
                    return "application/vnd.wolfram.player";
                case "ncx":
                    return "application/x-dtbncx+xml";
                case "nfo":
                    return "text/x-nfo";
                case "ngdat":
                    return "application/vnd.nokia.n-gage.data";
                case "nitf":
                case "ntf":
                    return "application/vnd.nitf";
                case "nlu":
                    return "application/vnd.neurolanguage.nlu";
                case "nml":
                    return "application/vnd.enliven";
                case "nnd":
                    return "application/vnd.noblenet-directory";
                case "nns":
                    return "application/vnd.noblenet-sealer";
                case "nnw":
                    return "application/vnd.noblenet-web";
                case "npx":
                    return "image/vnd.net-fpx";
                case "nq":
                    return "application/n-quads";
                case "nsc":
                    return "application/x-conference";
                case "nsf":
                    return "application/vnd.lotus-notes";
                case "nt":
                    return "application/n-triples";
                case "nzb":
                    return "application/x-nzb";
                case "oa2":
                    return "application/vnd.fujitsu.oasys2";
                case "oa3":
                    return "application/vnd.fujitsu.oasys3";
                case "oas":
                    return "application/vnd.fujitsu.oasys";
                case "obd":
                    return "application/x-msbinder";
                case "obj":
                    return "application/x-tgif";
                case "oda":
                    return "application/oda";
                case "odb":
                    return "application/vnd.oasis.opendocument.database";
                case "odc":
                    return "application/vnd.oasis.opendocument.chart";
                case "odf":
                    return "application/vnd.oasis.opendocument.formula";
                case "odft":
                    return "application/vnd.oasis.opendocument.formula-template";
                case "odg":
                    return "application/vnd.oasis.opendocument.graphics";
                case "odi":
                    return "application/vnd.oasis.opendocument.image";
                case "odm":
                    return "application/vnd.oasis.opendocument.text-master";
                case "odp":
                    return "application/vnd.oasis.opendocument.presentation";
                case "ods":
                    return "application/vnd.oasis.opendocument.spreadsheet";
                case "odt":
                    return "application/vnd.oasis.opendocument.text";
                case "oex":
                    return "application/x-opera-extension";
                case "oga":
                case "ogg":
                case "opus":
                case "spx":
                    return "audio/ogg";
                case "ogv":
                    return "video/ogg";
                case "ogx":
                    return "application/ogg";
                case "omdoc":
                    return "application/omdoc+xml";
                case "onepkg":
                case "onetmp":
                case "onetoc":
                case "onetoc2":
                    return "application/onenote";
                case "opf":
                    return "application/oebps-package+xml";
                case "opml":
                    return "text/x-opml";
                case "oprc":
                case "pdb":
                case "pqa":
                    return "application/vnd.palm";
                case "org":
                    return "application/vnd.lotus-organizer";
                case "osf":
                    return "application/vnd.yamaha.openscoreformat";
                case "osfpvg":
                    return "application/vnd.yamaha.openscoreformat.osfpvg+xml";
                case "otc":
                    return "application/vnd.oasis.opendocument.chart-template";
                case "otf":
                    return "font/otf";
                case "otg":
                    return "application/vnd.oasis.opendocument.graphics-template";
                case "oth":
                    return "application/vnd.oasis.opendocument.text-web";
                case "oti":
                    return "application/vnd.oasis.opendocument.image-template";
                case "otp":
                    return "application/vnd.oasis.opendocument.presentation-template";
                case "ots":
                    return "application/vnd.oasis.opendocument.spreadsheet-template";
                case "ott":
                    return "application/vnd.oasis.opendocument.text-template";
                case "ova":
                    return "application/x-virtualbox-ova";
                case "ovf":
                    return "application/x-virtualbox-ovf";
                case "owl":
                case "rdf":
                    return "application/rdf+xml";
                case "oxps":
                    return "application/oxps";
                case "oxt":
                    return "application/vnd.openofficeorg.extension";
                case "p":
                case "pas":
                    return "text/x-pascal";
                case "p10":
                    return "application/pkcs10";
                case "p12":
                case "pfx":
                    return "application/x-pkcs12";
                case "p7b":
                case "spc":
                    return "application/x-pkcs7-certificates";
                case "p7c":
                case "p7m":
                    return "application/pkcs7-mime";
                case "p7r":
                    return "application/x-pkcs7-certreqresp";
                case "p7s":
                    return "application/pkcs7-signature";
                case "p8":
                    return "application/pkcs8";
                case "pac":
                    return "application/x-ns-proxy-autoconfig";
                case "paw":
                    return "application/vnd.pawaafile";
                case "pbd":
                    return "application/vnd.powerbuilder6";
                case "pbm":
                    return "image/x-portable-bitmap";
                case "pcf":
                    return "application/x-font-pcf";
                case "pcl":
                    return "application/vnd.hp-pcl";
                case "pclxl":
                    return "application/vnd.hp-pclxl";
                case "pct":
                case "pic":
                    return "image/x-pict";
                case "pcurl":
                    return "application/vnd.curl.pcurl";
                case "pcx":
                    return "image/x-pcx";
                case "pde":
                    return "text/x-processing";
                case "pdf":
                    return "application/pdf";
                case "pfr":
                    return "application/font-tdpfr";
                case "pgm":
                    return "image/x-portable-graymap";
                case "pgn":
                    return "application/x-chess-pgn";
                case "pgp":
                    return "application/pgp-encrypted";
                case "php":
                    return "application/x-httpd-php";
                case "pki":
                    return "application/pkixcmp";
                case "pkipath":
                    return "application/pkix-pkipath";
                case "pkpass":
                    return "application/vnd.apple.pkpass";
                case "pl":
                case "pm":
                    return "application/x-perl";
                case "plb":
                    return "application/vnd.3gpp.pic-bw-large";
                case "plc":
                    return "application/vnd.mobius.plc";
                case "plf":
                    return "application/vnd.pocketlearn";
                case "pls":
                    return "application/pls+xml";
                case "pml":
                    return "application/vnd.ctc-posml";
                case "png":
                    return "image/png";
                case "pnm":
                    return "image/x-portable-anymap";
                case "portpkg":
                    return "application/vnd.macports.portpkg";
                case "pot":
                case "pps":
                case "ppt":
                    return "application/vnd.ms-powerpoint";
                case "potm":
                    return "application/vnd.ms-powerpoint.template.macroenabled.12";
                case "potx":
                    return "application/vnd.openxmlformats-officedocument.presentationml.template";
                case "ppam":
                    return "application/vnd.ms-powerpoint.addin.macroenabled.12";
                case "ppd":
                    return "application/vnd.cups-ppd";
                case "ppm":
                    return "image/x-portable-pixmap";
                case "ppsm":
                    return "application/vnd.ms-powerpoint.slideshow.macroenabled.12";
                case "ppsx":
                    return "application/vnd.openxmlformats-officedocument.presentationml.slideshow";
                case "pptm":
                    return "application/vnd.ms-powerpoint.presentation.macroenabled.12";
                case "pptx":
                    return "application/vnd.openxmlformats-officedocument.presentationml.presentation";
                case "pre":
                    return "application/vnd.lotus-freelance";
                case "prf":
                    return "application/pics-rules";
                case "psb":
                    return "application/vnd.3gpp.pic-bw-small";
                case "psd":
                    return "image/vnd.adobe.photoshop";
                case "psf":
                    return "application/x-font-linux-psf";
                case "pskcxml":
                    return "application/pskc+xml";
                case "ptid":
                    return "application/vnd.pvi.ptid1";
                case "pub":
                    return "application/x-mspublisher";
                case "pvb":
                    return "application/vnd.3gpp.pic-bw-var";
                case "pwn":
                    return "application/vnd.3m.post-it-notes";
                case "pya":
                    return "audio/vnd.ms-playready.media.pya";
                case "pyv":
                    return "video/vnd.ms-playready.media.pyv";
                case "qam":
                    return "application/vnd.epson.quickanime";
                case "qbo":
                    return "application/vnd.intu.qbo";
                case "qfx":
                    return "application/vnd.intu.qfx";
                case "qps":
                    return "application/vnd.publishare-delta-tree";
                case "qwd":
                case "qwt":
                case "qxb":
                case "qxd":
                case "qxl":
                case "qxt":
                    return "application/vnd.quark.quarkxpress";
                case "ra":
                case "ram":
                    return "audio/x-pn-realaudio";
                case "raml":
                    return "application/raml+yaml";
                case "rar":
                    return "application/x-rar-compressed";
                case "ras":
                    return "image/x-cmu-raster";
                case "rcprofile":
                    return "application/vnd.ipunplugged.rcprofile";
                case "rdz":
                    return "application/vnd.data-vision.rdz";
                case "rep":
                    return "application/vnd.businessobjects";
                case "res":
                    return "application/x-dtbresource+xml";
                case "rgb":
                    return "image/x-rgb";
                case "rif":
                    return "application/reginfo+xml";
                case "rip":
                    return "audio/vnd.rip";
                case "ris":
                    return "application/x-research-info-systems";
                case "rl":
                    return "application/resource-lists+xml";
                case "rlc":
                    return "image/vnd.fujixerox.edmics-rlc";
                case "rld":
                    return "application/resource-lists-diff+xml";
                case "rm":
                    return "application/vnd.rn-realmedia";
                case "rmp":
                    return "audio/x-pn-realaudio-plugin";
                case "rms":
                    return "application/vnd.jcp.javame.midlet-rms";
                case "rmvb":
                    return "application/vnd.rn-realmedia-vbr";
                case "rnc":
                    return "application/relax-ng-compact-syntax";
                case "rng":
                case "xml":
                case "xsd":
                case "xsl":
                    return "application/xml";
                case "roa":
                    return "application/rpki-roa";
                case "rp9":
                    return "application/vnd.cloanto.rp9";
                case "rpm":
                    return "application/x-redhat-package-manager";
                case "rpss":
                    return "application/vnd.nokia.radio-presets";
                case "rpst":
                    return "application/vnd.nokia.radio-preset";
                case "rq":
                    return "application/sparql-query";
                case "rs":
                    return "application/rls-services+xml";
                case "rsd":
                    return "application/rsd+xml";
                case "rss":
                    return "application/rss+xml";
                case "rtf":
                    return "application/rtf";
                case "rtx":
                    return "text/richtext";
                case "run":
                    return "application/x-makeself";
                case "s3m":
                    return "audio/s3m";
                case "saf":
                    return "application/vnd.yamaha.smaf-audio";
                case "sass":
                    return "text/x-sass";
                case "sbml":
                    return "application/sbml+xml";
                case "sc":
                    return "application/vnd.ibm.secure-container";
                case "scd":
                    return "application/x-msschedule";
                case "scm":
                    return "application/vnd.lotus-screencam";
                case "scq":
                    return "application/scvp-cv-request";
                case "scs":
                    return "application/scvp-cv-response";
                case "scss":
                    return "text/x-scss";
                case "scurl":
                    return "text/vnd.curl.scurl";
                case "sda":
                    return "application/vnd.stardivision.draw";
                case "sdc":
                    return "application/vnd.stardivision.calc";
                case "sdd":
                    return "application/vnd.stardivision.impress";
                case "sdkd":
                case "sdkm":
                    return "application/vnd.solent.sdkm+xml";
                case "sdp":
                    return "application/sdp";
                case "sdw":
                case "vor":
                    return "application/vnd.stardivision.writer";
                case "sea":
                    return "application/x-sea";
                case "see":
                    return "application/vnd.seemail";
                case "sema":
                    return "application/vnd.sema";
                case "semd":
                    return "application/vnd.semd";
                case "semf":
                    return "application/vnd.semf";
                case "ser":
                    return "application/java-serialized-object";
                case "setpay":
                    return "application/set-payment-initiation";
                case "setreg":
                    return "application/set-registration-initiation";
                case "sfd-hdstx":
                    return "application/vnd.hydrostatix.sof-data";
                case "sfs":
                    return "application/vnd.spotfire.sfs";
                case "sfv":
                    return "text/x-sfv";
                case "sgi":
                    return "image/sgi";
                case "sgl":
                    return "application/vnd.stardivision.writer-global";
                case "sgm":
                case "sgml":
                    return "text/sgml";
                case "sh":
                    return "application/x-sh";
                case "shar":
                    return "application/x-shar";
                case "shex":
                    return "text/shex";
                case "shf":
                    return "application/shf+xml";
                case "sid":
                    return "image/x-mrsid-image";
                case "sieve":
                case "siv":
                    return "application/sieve";
                case "sil":
                    return "audio/silk";
                case "sis":
                case "sisx":
                    return "application/vnd.symbian.install";
                case "sit":
                    return "application/x-stuffit";
                case "sitx":
                    return "application/x-stuffitx";
                case "skd":
                case "skm":
                case "skp":
                case "skt":
                    return "application/vnd.koan";
                case "sldm":
                    return "application/vnd.ms-powerpoint.slide.macroenabled.12";
                case "sldx":
                    return "application/vnd.openxmlformats-officedocument.presentationml.slide";
                case "slim":
                case "slm":
                    return "text/slim";
                case "slt":
                    return "application/vnd.epson.salt";
                case "sm":
                    return "application/vnd.stepmania.stepchart";
                case "smf":
                    return "application/vnd.stardivision.math";
                case "smi":
                case "smil":
                    return "application/smil+xml";
                case "smv":
                    return "video/x-smv";
                case "smzip":
                    return "application/vnd.stepmania.package";
                case "snf":
                    return "application/x-font-snf";
                case "spf":
                    return "application/vnd.yamaha.smaf-phrase";
                case "spl":
                    return "application/x-futuresplash";
                case "spot":
                    return "text/vnd.in3d.spot";
                case "spp":
                    return "application/scvp-vp-response";
                case "spq":
                    return "application/scvp-vp-request";
                case "sql":
                    return "application/x-sql";
                case "src":
                    return "application/x-wais-source";
                case "srt":
                    return "application/x-subrip";
                case "sru":
                    return "application/sru+xml";
                case "srx":
                    return "application/sparql-results+xml";
                case "ssdl":
                    return "application/ssdl+xml";
                case "sse":
                    return "application/vnd.kodak-descriptor";
                case "ssf":
                    return "application/vnd.epson.ssf";
                case "ssml":
                    return "application/ssml+xml";
                case "st":
                    return "application/vnd.sailingtracker.track";
                case "stc":
                    return "application/vnd.sun.xml.calc.template";
                case "std":
                    return "application/vnd.sun.xml.draw.template";
                case "stf":
                    return "application/vnd.wt.stf";
                case "sti":
                    return "application/vnd.sun.xml.impress.template";
                case "stk":
                    return "application/hyperstudio";
                case "stl":
                    return "application/vnd.ms-pki.stl";
                case "str":
                    return "application/vnd.pg.format";
                case "stw":
                    return "application/vnd.sun.xml.writer.template";
                case "styl":
                case "stylus":
                    return "text/stylus";
                case "sub":
                    return "image/vnd.dvb.subtitle";
                case "sus":
                case "susp":
                    return "application/vnd.sus-calendar";
                case "sv4cpio":
                    return "application/x-sv4cpio";
                case "sv4crc":
                    return "application/x-sv4crc";
                case "svc":
                    return "application/vnd.dvb.service";
                case "svd":
                    return "application/vnd.svd";
                case "svg":
                case "svgz":
                    return "image/svg+xml";
                case "swf":
                    return "application/x-shockwave-flash";
                case "swi":
                    return "application/vnd.aristanetworks.swi";
                case "sxc":
                    return "application/vnd.sun.xml.calc";
                case "sxd":
                    return "application/vnd.sun.xml.draw";
                case "sxg":
                    return "application/vnd.sun.xml.writer.global";
                case "sxi":
                    return "application/vnd.sun.xml.impress";
                case "sxm":
                    return "application/vnd.sun.xml.math";
                case "sxw":
                    return "application/vnd.sun.xml.writer";
                case "t3":
                    return "application/x-t3vm-image";
                case "taglet":
                    return "application/vnd.mynfc";
                case "tao":
                    return "application/vnd.tao.intent-module-archive";
                case "tar":
                    return "application/x-tar";
                case "tcap":
                    return "application/vnd.3gpp2.tcap";
                case "tcl":
                case "tk":
                    return "application/x-tcl";
                case "teacher":
                    return "application/vnd.smart.teacher";
                case "tei":
                case "teicorpus":
                    return "application/tei+xml";
                case "tex":
                    return "application/x-tex";
                case "texi":
                case "texinfo":
                    return "application/x-texinfo";
                case "tfi":
                    return "application/thraud+xml";
                case "tfm":
                    return "application/x-tex-tfm";
                case "tga":
                    return "image/x-tga";
                case "thmx":
                    return "application/vnd.ms-officetheme";
                case "tif":
                case "tiff":
                    return "image/tiff";
                case "tmo":
                    return "application/vnd.tmobile-livetv";
                case "toml":
                    return "application/toml";
                case "torrent":
                    return "application/x-bittorrent";
                case "tpl":
                    return "application/vnd.groove-tool-template";
                case "tpt":
                    return "application/vnd.trid.tpt";
                case "tra":
                    return "application/vnd.trueapp";
                case "trm":
                    return "application/x-msterminal";
                case "tsd":
                    return "application/timestamped-data";
                case "tsv":
                    return "text/tab-separated-values";
                case "ttc":
                    return "font/collection";
                case "ttf":
                    return "font/ttf";
                case "ttl":
                    return "text/turtle";
                case "twd":
                case "twds":
                    return "application/vnd.simtech-mindmapper";
                case "txd":
                    return "application/vnd.genomatix.tuxedo";
                case "txf":
                    return "application/vnd.mobius.txf";
                case "ufd":
                case "ufdl":
                    return "application/vnd.ufdl";
                case "ulx":
                    return "application/x-glulx";
                case "umj":
                    return "application/vnd.umajin";
                case "unityweb":
                    return "application/vnd.unity";
                case "uoml":
                    return "application/vnd.uoml+xml";
                case "uri":
                case "uris":
                case "urls":
                    return "text/uri-list";
                case "ustar":
                    return "application/x-ustar";
                case "utz":
                    return "application/vnd.uiq.theme";
                case "uu":
                    return "text/x-uuencode";
                case "uva":
                case "uvva":
                    return "audio/vnd.dece.audio";
                case "uvd":
                case "uvf":
                case "uvvd":
                case "uvvf":
                    return "application/vnd.dece.data";
                case "uvg":
                case "uvi":
                case "uvvg":
                case "uvvi":
                    return "image/vnd.dece.graphic";
                case "uvh":
                case "uvvh":
                    return "video/vnd.dece.hd";
                case "uvm":
                case "uvvm":
                    return "video/vnd.dece.mobile";
                case "uvp":
                case "uvvp":
                    return "video/vnd.dece.pd";
                case "uvs":
                case "uvvs":
                    return "video/vnd.dece.sd";
                case "uvt":
                case "uvvt":
                    return "application/vnd.dece.ttml+xml";
                case "uvu":
                case "uvvu":
                    return "video/vnd.uvvu.mp4";
                case "uvv":
                case "uvvv":
                    return "video/vnd.dece.video";
                case "uvvx":
                case "uvx":
                    return "application/vnd.dece.unspecified";
                case "uvvz":
                case "uvz":
                    return "application/vnd.dece.zip";
                case "vbox":
                    return "application/x-virtualbox-vbox";
                case "vbox-extpack":
                    return "application/x-virtualbox-vbox-extpack";
                case "vcard":
                    return "text/vcard";
                case "vcd":
                    return "application/x-cdlink";
                case "vcf":
                    return "text/x-vcard";
                case "vcg":
                    return "application/vnd.groove-vcard";
                case "vcs":
                    return "text/x-vcalendar";
                case "vcx":
                    return "application/vnd.vcx";
                case "vdi":
                    return "application/x-virtualbox-vdi";
                case "vhd":
                    return "application/x-virtualbox-vhd";
                case "vis":
                    return "application/vnd.visionary";
                case "viv":
                    return "video/vnd.vivo";
                case "vmdk":
                    return "application/x-virtualbox-vmdk";
                case "vob":
                    return "video/x-ms-vob";
                case "vrml":
                case "wrl":
                    return "model/vrml";
                case "vsd":
                case "vss":
                case "vst":
                case "vsw":
                    return "application/vnd.visio";
                case "vsf":
                    return "application/vnd.vsf";
                case "vtt":
                    return "text/vtt";
                case "vtu":
                    return "model/vnd.vtu";
                case "vxml":
                    return "application/voicexml+xml";
                case "wad":
                    return "application/x-doom";
                case "wadl":
                    return "application/vnd.sun.wadl+xml";
                case "wasm":
                    return "application/wasm";
                case "wav":
                    return "audio/x-wav";
                case "wax":
                    return "audio/x-ms-wax";
                case "wbmp":
                    return "image/vnd.wap.wbmp";
                case "wbs":
                    return "application/vnd.criticaltools.wbs+xml";
                case "wbxml":
                    return "application/vnd.wap.wbxml";
                case "wcm":
                case "wdb":
                case "wks":
                case "wps":
                    return "application/vnd.ms-works";
                case "wdp":
                    return "image/vnd.ms-photo";
                case "weba":
                    return "audio/webm";
                case "webapp":
                    return "application/x-web-app-manifest+json";
                case "webm":
                    return "video/webm";
                case "webmanifest":
                    return "application/manifest+json";
                case "webp":
                    return "image/webp";
                case "wg":
                    return "application/vnd.pmi.widget";
                case "wgt":
                    return "application/widget";
                case "wm":
                    return "video/x-ms-wm";
                case "wma":
                    return "audio/x-ms-wma";
                case "wmd":
                    return "application/x-ms-wmd";
                case "wml":
                    return "text/vnd.wap.wml";
                case "wmlc":
                    return "application/vnd.wap.wmlc";
                case "wmls":
                    return "text/vnd.wap.wmlscript";
                case "wmlsc":
                    return "application/vnd.wap.wmlscriptc";
                case "wmv":
                    return "video/x-ms-wmv";
                case "wmx":
                    return "video/x-ms-wmx";
                case "wmz":
                    return "application/x-ms-wmz";
                case "woff":
                    return "font/woff";
                case "woff2":
                    return "font/woff2";
                case "wpd":
                    return "application/vnd.wordperfect";
                case "wpl":
                    return "application/vnd.ms-wpl";
                case "wqd":
                    return "application/vnd.wqd";
                case "wri":
                    return "application/x-mswrite";
                case "wsdl":
                    return "application/wsdl+xml";
                case "wspolicy":
                    return "application/wspolicy+xml";
                case "wtb":
                    return "application/vnd.webturbo";
                case "wvx":
                    return "video/x-ms-wvx";
                case "x3d":
                case "x3dz":
                    return "model/x3d+xml";
                case "x3db":
                case "x3dbz":
                    return "model/x3d+binary";
                case "x3dv":
                case "x3dvz":
                    return "model/x3d+vrml";
                case "xaml":
                    return "application/xaml+xml";
                case "xap":
                    return "application/x-silverlight-app";
                case "xar":
                    return "application/vnd.xara";
                case "xbap":
                    return "application/x-ms-xbap";
                case "xbd":
                    return "application/vnd.fujixerox.docuworks.binder";
                case "xbm":
                    return "image/x-xbitmap";
                case "xdf":
                    return "application/xcap-diff+xml";
                case "xdm":
                    return "application/vnd.syncml.dm+xml";
                case "xdp":
                    return "application/vnd.adobe.xdp+xml";
                case "xdssc":
                    return "application/dssc+xml";
                case "xdw":
                    return "application/vnd.fujixerox.docuworks";
                case "xenc":
                    return "application/xenc+xml";
                case "xer":
                    return "application/patch-ops-error+xml";
                case "xfdf":
                    return "application/vnd.adobe.xfdf";
                case "xfdl":
                    return "application/vnd.xfdl";
                case "xht":
                case "xhtml":
                    return "application/xhtml+xml";
                case "xif":
                    return "image/vnd.xiff";
                case "xla":
                case "xlc":
                case "xlm":
                case "xls":
                case "xlt":
                case "xlw":
                    return "application/vnd.ms-excel";
                case "xlam":
                    return "application/vnd.ms-excel.addin.macroenabled.12";
                case "xlf":
                    return "application/x-xliff+xml";
                case "xloc":
                    return "text/vnd.rim.location.xloc";
                case "xlsb":
                    return "application/vnd.ms-excel.sheet.binary.macroenabled.12";
                case "xlsm":
                    return "application/vnd.ms-excel.sheet.macroenabled.12";
                case "xlsx":
                    return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                case "xltm":
                    return "application/vnd.ms-excel.template.macroenabled.12";
                case "xltx":
                    return "application/vnd.openxmlformats-officedocument.spreadsheetml.template";
                case "xm":
                    return "audio/xm";
                case "xo":
                    return "application/vnd.olpc-sugar";
                case "xop":
                    return "application/xop+xml";
                case "xpi":
                    return "application/x-xpinstall";
                case "xpl":
                    return "application/xproc+xml";
                case "xpm":
                    return "image/x-xpixmap";
                case "xpr":
                    return "application/vnd.is-xpr";
                case "xps":
                    return "application/vnd.ms-xpsdocument";
                case "xpw":
                case "xpx":
                    return "application/vnd.intercon.formnet";
                case "xslt":
                    return "application/xslt+xml";
                case "xsm":
                    return "application/vnd.syncml+xml";
                case "xspf":
                    return "application/xspf+xml";
                case "xul":
                    return "application/vnd.mozilla.xul+xml";
                case "xwd":
                    return "image/x-xwindowdump";
                case "xyz":
                    return "chemical/x-xyz";
                case "xz":
                    return "application/x-xz";
                case "yaml":
                case "yml":
                    return "text/yaml";
                case "yang":
                    return "application/yang";
                case "yin":
                    return "application/yin+xml";
                case "ymp":
                    return "text/x-suse-ymp";
                case "z1":
                case "z2":
                case "z3":
                case "z4":
                case "z5":
                case "z6":
                case "z7":
                case "z8":
                    return "application/x-zmachine";
                case "zaz":
                    return "application/vnd.zzazz.deck+xml";
                case "zip":
                    return "application/zip";
                case "zir":
                case "zirz":
                    return "application/vnd.zul";
                case "zmm":
                    return "application/vnd.handheld-entertainment+xml";
                default:
                    return (string) null;
            }
        }
    }
}
