name: MediaConverters

on: [push]

jobs:

  BuildOnLinux:

    runs-on: ubuntu-latest
    container:
      image: debian:buster-slim

    steps:
    - name: UpdateSource
      run: |
          rm /etc/apt/sources.list
          echo 'deb http://archive.debian.org/debian buster main contrib non-free'  >> /etc/apt/sources.list
    - name: InstallTool
      run: |
          dpkg --add-architecture arm64
          apt-get update
          apt-get install libicu-dev -y
          apt-get install libssl-dev -y
          apt-get install wget -y
          apt-get install curl -y
          apt-get install clang llvm -y
          apt-get install gcc-aarch64-linux-gnu -y
          apt-get install binutils-aarch64-linux-gnu -y
          apt-get install zlib1g-dev -y
          apt-get install zlib1g-dev:arm64 -y

    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x

    - name: Publish and Pack linux-arm64
      run: |
        dotnet publish -c Release -r linux-arm64 src/MediaConverters/MediaConverters.Tool/MediaConverters.Tool.csproj
        dotnet pack --configuration Release /p:RuntimeIdentifier=linux-arm64 src/MediaConverters/MediaConverters.Tool.RuntimeNuGet/MediaConverters.Tool.RuntimeNuGet.csproj
    
    - uses: actions/upload-artifact@v4
      name: UploadArtifact
      with:
        name: linux-arm64
        path: bin/Release/
        retention-days: 1

   # dotnet nuget push ./bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NugetKey }}
