name: MediaConverters

on: [push]

jobs:

  BuildOnLinux:

    runs-on: ubuntu-latest
    container:
      image: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x

    - name: Publish and Pack linux-x64
      run: |
        dotnet publish -c Release -r linux-x64 src/MediaConverters/MediaConverters.Tool/MediaConverters.Tool.csproj
        dotnet pack --configuration Release /p:RuntimeIdentifier=linux-x64 src/MediaConverters/MediaConverters.Tool.RuntimeNuGet/MediaConverters.Tool.RuntimeNuGet.csproj
    
    - uses: actions/upload-artifact@v4
      name: UploadArtifact
      with:
        name: linux-x64
        path: bin/Release/
        retention-days: 1

   # dotnet nuget push ./bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NugetKey }}
