name: Publish MediaConverters NuGet

on: 
  push:
    tags:
    - '*'

jobs:
  PackOnWindows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
 
    - name: Install dotnet tool
      run: dotnet tool install -g dotnetCampus.TagToVersion

    - name: Set tag to version  
      run: dotnet TagToVersion -t ${{ github.ref }}

    - name: Build with dotnet
      run: dotnet build --configuration Release src\MediaConverters\MediaConverters.sln

    - name: Publish and Pack win-x86
      run: |
        dotnet publish -c Release -r win-x86 src\MediaConverters\MediaConverters.Tool\MediaConverters.Tool.csproj
        dotnet pack --configuration Release /p:RuntimeIdentifier=win-x86 src\MediaConverters\MediaConverters.RuntimeNuGet\MediaConverters.RuntimeNuGet.csproj

    - name: Publish and Pack win-x64
      run: |
        dotnet publish -c Release -r win-x64 src\MediaConverters\MediaConverters.Tool\MediaConverters.Tool.csproj
        dotnet pack --configuration Release /p:RuntimeIdentifier=win-x64 src\MediaConverters\MediaConverters.RuntimeNuGet\MediaConverters.RuntimeNuGet.csproj

    - name: Add private GitHub registry to NuGet
      run: |
        dotnet nuget add sources --username dotnet-campus --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dotnet-campus/index.json"

    - name: Push generated package to NuGet 
      run: |
        dotnet nuget push .\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NugetKey }}
        dotnet nuget push .\bin\Release\*.nupkg -s github
